# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36c6a6ed6db9fde79c9a8236a6d28faff2612005a8f69c6e87d6842f5a6ea67d17175a36017ad719cc1e604648905ee3020c78c1a01e323117c75849d2be8efd

test:
  secret_key_base: 14933c1ef9dd56fd218206959f0abdafd73c4ba81098d059da9259291e67c4e564772411474a771b8cbbf8ae4e3850eb8aa9a405e73d8c9025dcc9aee10ed6fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
